// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
const std = @import("std");
const libpas_sources = @import("src/runtime/libpas_sources.zig");
const musl_headers = @import("src/gen/musl_headers.zig");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // zailc-gen: the generators Fil-C's runtime build needs (the forwarder generator, musl's
    // header install).
    const gen = b.addExecutable(.{
        .name = "zailc-gen",
        .root_module = b.createModule(.{
            .root_source_file = b.path("src/gen/main.zig"),
            .target = target,
            .optimize = optimize,
        }),
    });
    b.installArtifact(gen);

    // `zig build gen -- header out.h` / `zig build gen -- forwarders out.c` / `... musl-headers …`
    const run_gen = b.addRunArtifact(gen);
    if (b.args) |args| run_gen.addArgs(args);
    b.step("gen", "Run zailc-gen with the arguments after --").dependOn(&run_gen.step);

    // `zig build test`: the byte-identity tests (SHA-256 of both forwarder outputs against
    // Ruby's) and the musl header rules.
    const test_step = b.step("test", "Run the unit tests");
    for ([_][]const u8{ "src/gen/forwarders.zig", "src/gen/musl_headers.zig" }) |root| {
        const t = b.addTest(.{
            .root_module = b.createModule(.{
                .root_source_file = b.path(root),
                .target = target,
                .optimize = optimize,
            }),
        });
        test_step.dependOn(&b.addRunArtifact(t).step);
    }

    // `zig build libpas -Dfilc-src=<Fil-C tree> [-Dpizfix=<pizfix>]`: the stock-compiled half of
    // Fil-C's runtime, libpizlo-stock.a, from upstream's sources, compiled by Zig's clang with the
    // flags of libpas/Makefile (PASCC + PASCFLAGS, static variant). The three Fil-C-compiled
    // pieces (filc/src) are not in it yet (cmem/roadmap.md).
    const filc_src = b.option([]const u8, "filc-src", "A Fil-C v0.686 source tree to compile the runtime from");
    const pizfix_opt = b.option([]const u8, "pizfix", "A pizfix/ with os-include and stdfil-include (default: <filc-src>/pizfix)");
    const libpas_step = b.step("libpas", "Build the stock half of Fil-C's runtime from -Dfilc-src: libpizlo-stock.a, filc_crt.o, filc_mincrt.o, libyolounwind.a");
    if (filc_src) |src| {
        buildStockRuntime(b, libpas_step, gen, src, pizfix_opt orelse b.pathJoin(&.{ src, "pizfix" }));
    } else {
        libpas_step.dependOn(&b.addFail("zig build libpas needs -Dfilc-src=<path to a Fil-C v0.686 tree>").step);
    }
}

/// The settings every stock-compiled runtime object shares: upstream compiles them with its
/// host clang for x86_64 Linux, -fPIC, no sanitizers, with debug info.
fn runtimeModule(b: *std.Build, cpu: std.Target.Query.CpuModel, pic: bool) *std.Build.Module {
    return b.createModule(.{
        .target = b.resolveTargetQuery(.{
            .cpu_arch = .x86_64,
            .os_tag = .linux,
            .abi = .none, // no libc from Zig: musl's headers come from yolo-include, as upstream
            .cpu_model = cpu,
        }),
        .optimize = .ReleaseFast,
        .pic = pic,
        .sanitize_c = .off, // upstream compiles with plain clang; no UBSan
        .strip = false, // -g
        .link_libc = false,
    });
}

fn buildStockRuntime(b: *std.Build, step: *std.Build.Step, gen: *std.Build.Step.Compile, filc_src: []const u8, pizfix: []const u8) void {
    const libpas_dir = b.pathJoin(&.{ filc_src, "libpas" });

    // pizfix/yolo-include: musl's installed headers, generated by zailc-gen from the yolomusl tree
    // (upstream: `make install` in projects/yolomusl, then `mv yolo/include yolo-include`).
    const musl_src = b.pathJoin(&.{ filc_src, "projects", "yolomusl" });
    const headers = b.addRunArtifact(gen);
    headers.addArg("musl-headers");
    headers.addArg(musl_src);
    const yolo_include = headers.addOutputDirectoryArg("yolo-include");
    headers.addArg("x86_64");
    // The step is cached by its arguments, and the musl tree is only a path among them: declare
    // every file zailc-gen reads as an input, from the same list it reads them by, so an edit in
    // the tree (or a pin move) reruns it (cmem/workarounds.md W-5).
    const header_inputs = musl_headers.inputs(b.allocator, musl_src, "x86_64") catch |err| {
        step.dependOn(&b.addFail(b.fmt("cannot list musl's headers in {s}: {s}", .{ musl_src, @errorName(err) })).step);
        return;
    };
    for (header_inputs) |in| headers.addFileInput(.{ .cwd_relative = b.pathJoin(&.{ musl_src, in.path }) });

    // The two generated sources (upstream: ruby, in-tree; here: into the cache, the tree stays
    // read-only). `filc_runtime.c` finds "filc_native.h" through the include path.
    const native_h = b.addRunArtifact(gen);
    native_h.addArg("header");
    const native_h_out = native_h.addOutputFileArg("filc_native.h");
    const fwd_c = b.addRunArtifact(gen);
    fwd_c.addArg("forwarders");
    const fwd_c_out = fwd_c.addOutputFileArg("filc_native_forwarders.c");

    // PASCC = clang -march=x86-64-v2 -fPIC -pthread -nostdinc -isystem yolo-include
    //         -isystem os-include -isystem stdfil-include -isystem <clang resource include>
    // PASCFLAGS = -g -O3 -W -Werror -fno-strict-aliasing (-MD)      plus -DPAS_FILC=1
    const v2: std.Target.Query.CpuModel = .{ .explicit = &std.Target.x86.cpu.x86_64_v2 }; // -march=x86-64-v2
    const mod = runtimeModule(b, v2, true);
    const pascc = [_][]const u8{ "-pthread", "-nostdinc", "-g", "-O3", "-W", "-Werror", "-fno-strict-aliasing" };
    // Upstream runs make in libpas/ and names sources `src/libpas/x.c`, so `__FILE__` (in every
    // PAS_ASSERT and panic message) reads `src/libpas/x.c`. Zig passes absolute paths; map them
    // back so the runtime's messages are upstream's (cmem/workarounds.md W-6).
    const libpas_map = b.fmt("-ffile-prefix-map={s}/=", .{libpas_dir});
    const cflags = b.allocator.dupe([]const u8, &(pascc ++ [_][]const u8{ "-DPAS_FILC=1", libpas_map })) catch @panic("OOM");
    const addPasccIncludes = struct {
        fn f(m: *std.Build.Module, bb: *std.Build, yolo: std.Build.LazyPath, piz: []const u8) void {
            m.addSystemIncludePath(yolo);
            m.addSystemIncludePath(.{ .cwd_relative = bb.pathJoin(&.{ piz, "os-include" }) });
            m.addSystemIncludePath(.{ .cwd_relative = bb.pathJoin(&.{ piz, "stdfil-include" }) });
            // `./find_clang_include_dir.rb` → the clang resource headers Zig ships (stddef.h, stdarg.h, …).
            m.addSystemIncludePath(.{ .cwd_relative = bb.pathJoin(&.{ bb.graph.zig_lib_directory.path orelse ".", "include" }) });
        }
    }.f;
    addPasccIncludes(mod, b, yolo_include, pizfix);
    mod.addIncludePath(native_h_out.dirname());
    mod.addIncludePath(.{ .cwd_relative = b.pathJoin(&.{ libpas_dir, "src", "libpas" }) });

    const root: std.Build.LazyPath = .{ .cwd_relative = libpas_dir };
    mod.addCSourceFiles(.{ .root = root, .files = &libpas_sources.c, .flags = cflags });
    // PASASM = clang -march=x86-64-v2 -fPIC, no PASASMFLAGS.
    mod.addCSourceFiles(.{ .root = root, .files = &libpas_sources.assembly, .flags = &.{} });
    mod.addCSourceFile(.{ .file = fwd_c_out, .flags = cflags });
    // The static variant: PASPIZLOSTATICOBJS adds filc_static.o and filc_default_settings.o.
    mod.addCSourceFiles(.{ .root = root, .files = &.{ "src/libpas/filc_static.c", "src/libpas/filc_default_settings.c" }, .flags = cflags });

    const lib = b.addLibrary(.{ .name = "pizlo-stock", .root_module = mod, .linkage = .static });
    step.dependOn(&b.addInstallArtifact(lib, .{}).step);

    // filc_crt.o / filc_mincrt.o: $(PASCC) -c ../filc/main/main.c $(MAINCFLAGS) -DUSE_LIBC=1 / 0
    // (MAINCFLAGS = -g -O3 -W -Werror -fno-strict-aliasing, the same as PASCFLAGS without -MD).
    const main_c = b.pathJoin(&.{ filc_src, "filc", "main", "main.c" });
    for ([_]struct { name: []const u8, def: []const u8 }{
        .{ .name = "filc_crt", .def = "-DUSE_LIBC=1" },
        .{ .name = "filc_mincrt", .def = "-DUSE_LIBC=0" },
    }) |crt| {
        const m = runtimeModule(b, v2, true);
        addPasccIncludes(m, b, yolo_include, pizfix);
        // Upstream compiles it from libpas/ as `../filc/main/main.c`.
        const crt_map = b.fmt("-ffile-prefix-map={s}/=../", .{filc_src});
        m.addCSourceFile(.{ .file = .{ .cwd_relative = main_c }, .flags = b.allocator.dupe([]const u8, &(pascc ++ [_][]const u8{ crt.def, crt_map })) catch @panic("OOM") });
        const obj = b.addObject(.{ .name = crt.name, .root_module = m });
        step.dependOn(&b.addInstallFile(obj.getEmittedBin(), b.fmt("lib/{s}.o", .{crt.name})).step);
    }

    // libyolounwind.a: `clang -c yolounwind.c -O2 -g` with the host's defaults (baseline x86-64,
    // no -fPIC), then `ar cr`. Six trap stubs; the file includes nothing.
    const unwind = runtimeModule(b, .baseline, false);
    // Upstream compiles it from yolounwind/ as `yolounwind.c`.
    const unwind_map = b.fmt("-ffile-prefix-map={s}/=", .{b.pathJoin(&.{ filc_src, "yolounwind" })});
    unwind.addCSourceFile(.{ .file = .{ .cwd_relative = b.pathJoin(&.{ filc_src, "yolounwind", "yolounwind.c" }) }, .flags = b.allocator.dupe([]const u8, &.{ "-O2", "-g", unwind_map }) catch @panic("OOM") });
    const unwind_lib = b.addLibrary(.{ .name = "yolounwind", .root_module = unwind, .linkage = .static });
    step.dependOn(&b.addInstallArtifact(unwind_lib, .{}).step);
}
