// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
//
// Derives src/runtime/libpas_sources.zig from libpas's common.mk (`PASSRCS`) and the `*.S`
// files next to them, so build.zig compiles exactly the files upstream's Makefile compiles.
// Re-run when the pin moves (tools/lib/tool.ts FILC_SHA).
//
//   deno run -A tools/runtime/import-libpas-sources.ts

import { FILC_SHA, FILC_VERSION, REPO, linuxOnly, must, requireFilcSrc, zig } from "../lib/tool.ts";

await linuxOnly(import.meta);

const src = await requireFilcSrc();
const mk = await Deno.readTextFile(`${src}/libpas/common.mk`);

// PASSRCS = \ <tab>src/libpas/a.c \ ... <tab>src/libpas/z.c
const m = mk.match(/^PASSRCS = \\\n((?:.*\\\n)*.*)$/m);
if (!m) throw new Error("PASSRCS not found in common.mk");
const all = m[1].split("\n").map((l) => l.replace(/\\$/, "").trim()).filter((l) => l.length);
const generated = all.filter((f) => f.endsWith("filc_native_forwarders.c"));
const c = all.filter((f) => !f.endsWith("filc_native_forwarders.c"));

// PASASMSRCS = $(sort $(wildcard src/libpas/*.S))
const asm: string[] = [];
for await (const e of Deno.readDir(`${src}/libpas/src/libpas`)) if (e.isFile && e.name.endsWith(".S")) asm.push(`src/libpas/${e.name}`);
asm.sort();

const z = (s: string) => JSON.stringify(s);
const list = (name: string, doc: string, items: string[]) =>
  [`/// ${doc}`, `pub const ${name} = [_][]const u8{`, ...items.map((f) => `    ${z(f)},`), "};", ""].join("\n");

const out = [
  "// GENERATED by tools/runtime/import-libpas-sources.ts. Do not edit: re-run the tool.",
  `// Source: Fil-C ${FILC_VERSION} (${FILC_SHA}), libpas/common.mk \`PASSRCS\` and libpas/src/libpas/*.S.`,
  "// Paths are relative to <filc-src>/libpas.",
  "",
  list("c", `\`PASSRCS\` minus the generated file (${c.length} files).`, c),
  list("generated", "In `PASSRCS` but generated at build time by zailc-gen (not read from the tree).", generated),
  list("assembly", "`PASASMSRCS`.", asm),
].join("\n");

const dest = `${REPO}/src/runtime/libpas_sources.zig`;
await Deno.mkdir(`${REPO}/src/runtime`, { recursive: true });
await Deno.writeTextFile(dest, out);
await must([zig(), "fmt", dest]);
console.log(`${dest}: ${c.length} C files + ${generated.length} generated + ${asm.length} assembly, from ${src}/libpas/common.mk`);
